# Generated by Django 3.1.3 on 2020-12-23 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0002_character_character_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='character',
            name='character_image',
            field=models.ImageField(blank=True, default='image/avatar.png', null=True, upload_to='image/'),
        ),
    ]
