# Generated by Django 3.1.3 on 2020-12-23 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='profile_image',
            field=models.ImageField(blank=True, default='image/avatar.png', null=True, upload_to='image/'),
        ),
    ]
