# Generated by Django 3.1.3 on 2021-02-16 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_auto_20210206_1307'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ban',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('pernamently', models.BooleanField(default=False)),
                ('until', models.DateTimeField()),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='user_bans',
            field=models.ManyToManyField(to='users.Ban'),
        ),
    ]
