# Generated by Django 3.1.3 on 2021-03-22 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_auto_20210216_1240'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profile_image',
            field=models.ImageField(blank=True, default='profile_images/avatar.png', null=True, upload_to='profile_images/'),
        ),
    ]
