# Generated by Django 3.1.3 on 2020-11-10 20:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Story',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=30)),
                ('plot', models.TextField()),
                ('is_rp', models.BooleanField(default=False)),
                ('number_of_users_in_story', models.IntegerField(choices=[(2, 'Two'), (3, 'Three'), (4, 'Four'), (5, 'Five')], default=2)),
                ('language', models.CharField(choices=[('PL', 'Polish'), ('EN', 'English'), ('DE', 'German')], default='EN', max_length=3)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('users_in_story', models.ManyToManyField(related_name='users_in_story', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
