# Generated by Django 3.1.3 on 2021-01-05 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0003_auto_20201223_1618'),
        ('stories', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='story',
            name='additional_characters',
            field=models.ManyToManyField(to='characters.Character'),
        ),
    ]
