# Generated by Django 3.1.3 on 2021-01-24 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stories', '0003_remove_story_is_rp'),
    ]

    operations = [
        migrations.AddField(
            model_name='story',
            name='female_number',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='story',
            name='male_number',
            field=models.IntegerField(default=0),
        ),
    ]
